### ISSUE TITLE
Timeseries - show in local timezone not UTC

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#14]
Currently timeseries calendar is showing in UTC.

Confusing for the user. Can we show in local timezone?

![image](https://cloud.githubusercontent.com/assets/534681/19163024/32aa5f3c-8bc8-11e6-92a5-2ffed1ef3070.png)

**Comment by jaclynadams** [comment]
Default for Pacific time shows long string "America/Los_Angeles" instead of "PST"/"PDT", which is too long to display there so I just removed the text and then use local time. Let me know if you think its a problem not to show timezone. I think that since it uses local time now we don't need to explicitly show it.
